### ISSUE TITLE
Utils don't load in Brave browser

### ISSUE THREAD

**Issue by Morgothek** [itzTheMeow/NinjaIOUtils#101]
Tempermonkey on, utils script installled and on, page refreshed and nothing, just like I didn't have them.
![image](https://github.com/user-attachments/assets/dbd01717-891f-4d1e-b88b-61ef07fd49c2)

**Comment by itzTheMeow** [comment]
Works for me on iOS safari, so it's not the script.
Check your tampermonkey pop up, is it making you enable "developer mode" or something similar? A screenshot of that would be appreciated.

**Comment by Morgothek** [comment]
Already fixed that, however I'm having another issue. My texture packs don't load. I created json file, all textures are named properly and they still don't load. 
[Fire.zip](https://github.com/user-attachments/files/16847577/Fire.zip)
Even more confusing is that a friend of mine said it works for him, however I can't see them in game. After uploading them and saving, game refreshes and nothing changes, still old textures are visible. I'm working on customization texture pack and really would like to test them in game before pulling requests here...
![image](https://github.com/user-attachments/assets/dd0a8959-d1b7-4eae-b50b-7fc28f6424d4)
![image](https://github.com/user-attachments/assets/455c3870-09da-4adc-bdac-e60370e0f39d)
![image](https://github.com/user-attachments/assets/2b424050-ba31-42ac-be03-bb21d1899dc2)

**Comment by itzTheMeow** [comment]
How was the issue fixed from before?On Sep 3, 2024, at 7:05 AM, Morgothek ***@***.***> wrote:﻿
Already fixed that, however I'm having another issue. My texture packs don't load. I created json file, all textures are named properly and they still don't load.
Fire.zip
Even more confusing is that a friend of mine said it works for him, however I can't see them in game. After uploading them and saving, game refreshes and nothing changes, still old textures are visible. I'm working on customization texture pack and really would like to test them in game before pulling requests here...
image.png (view on web)
image.png (view on web)
image.png (view on web)
