### ISSUE TITLE
Added texture pack game doesn't load

### ISSUE THREAD

**Issue by RainiPlayzYT** [itzTheMeow/NinjaIOUtils#104]
I have added a custom texture pack to my game and clicked on save and close, now my game doesn't load, the loading bar stops at halfway.
What should I do?

**Comment by itzTheMeow** [comment]
You can reset your settings by sending `delete localStorage.nutils_settings` in your developer console.

**Comment by RainiPlayzYT** [comment]
Could you tell me the process how to complete that?

**Comment by RainiPlayzYT** [comment]
Could tell me the steps on how to complete that?

**Comment by itzTheMeow** [comment]
open dev tools: https://developer.chrome.com/docs/devtools/open
click Console tab
paste that in, hit enter 
reload the page
