### ISSUE TITLE
(Question) New Texture Pack

### ISSUE THREAD

**Issue by Ninja-ioKarma** [itzTheMeow/NinjaIOUtils#81]
For my new texture pack, does it get added to where everyone can use it automatically or do I have to request it.

**Comment by Ninja-ioKarma** [comment]
(btw the texture pack is KarmasPinkTerror

**Comment by itzTheMeow** [comment]
sorry about that, packs should become available after i update the utils repo

i had some issues with updating it earlier
should be available for use now
