### ISSUE TITLE
NinjaIOUtils not working

### ISSUE THREAD

**Issue by Ninja-ioKarma** [itzTheMeow/NinjaIOUtils#90]
Just turned my computer on, and NinjaIOUtils texture packs are not appearing.
I have:
Reset Tab
Close and reopen Browser
Try a different Browser
Reset Cache
Reset Computer

None of it has worked.

**Comment by Ninja-ioKarma** [comment]
I have also tried re-installing NinjaIOUtils as well.

**Comment by Ninja-ioKarma** [comment]
@itzTheMeow

**Comment by itzTheMeow** [comment]
are there any errors in the browser console? press F12 => Console and reload the page

**Comment by Ninja-ioKarma** [comment]
> are there any errors in the browser console? press F12 => Console and reload the page

Yeah, there are tons of errors.

**Comment by itzTheMeow** [comment]
can you send them?

**Comment by Ninja-ioKarma** [comment]
Recorded all the errors in a yt vid @itzTheMeow 

https://www.youtube.com/watch?v=XetVgojVJWw

**Comment by itzTheMeow** [comment]
fixed
