### ISSUE TITLE
Game doesn't load with extension enabled

### ISSUE THREAD

**Issue by Topfpflanze777** [itzTheMeow/NinjaIOUtils#99]
Hello Meow,
my game doesn't load with extension enabled. I tried it in OperaGX and Chrome. After further investigations I got an error message from Chrome with is the following: "Stacktrace: content.js:30 (Anonyme Funktion)" and it pointed me to the following line of code: 
get:()=>(void 0===e&&(e=lo.extension.inIncognitoContext),e),set:t=>{e=t},enumerable:!0},...Object.getOwnPropertyDescriptors({getURL:function(e){return lo.runtime.getURL(e)},sendMessage:(e,t)=>lo.runtime.sendMessage(e,t),onMessage:{addListener:e=>lo.runtime.onMessage.addListener(e)},connect:e=>lo.runtime.connect({name:e})})})})(),bo=lo.userScripts&&lo.userScripts.onBeforeScript?{supported:!0,onBeforeScript:{addListener:e=>lo.userScripts.onBeforeScript.addListener(e)}}:{supported:!1 

It would be great if you could give me a solution to this problem. 

Yours sincerely, 
Nicolai

**Comment by Topfpflanze777** [comment]
Just an quick update, after 6 hours of tying I somehow (I don't know how) got my texturpack working. I think I loaded NinjaIOUtils while reloading the page and it somehow worked but after trying to realod I got stuck on the loading screen again.

**Comment by itzTheMeow** [comment]
Is the chrome error message the same as opera gx?
Does a texture pack fail to load or the entire script?

**Comment by itzTheMeow** [comment]
Also what version of chrome?

**Comment by Topfpflanze777** [comment]
![Bild_2024-06-28_105922845](https://github.com/itzTheMeow/NinjaIOUtils/assets/174017356/cea39408-3c92-4266-8587-ae03bd1d98af)
Thats the consolelog from OperaGX. And I use verion Version 126.0.6478.127 (Offizieller Build) (64-Bit)

**Comment by itzTheMeow** [comment]
looks like the script is loading though
![image](https://github.com/itzTheMeow/NinjaIOUtils/assets/50887230/605f7913-e3eb-4a63-932d-b98442e1b0e1)

try clearing cookies/cache and reloading the page

**Comment by Topfpflanze777** [comment]
ok

**Comment by Topfpflanze777** [comment]
ok I removed my texturpack now and Its loading but I still get a ton of error messages… Is that right?
![Uploading image.jpg…]()

**Comment by Topfpflanze777** [comment]
Hmmmm now I followed the steps your Taxtur Pack guid told me to do... But how can I use that texturpack now?

**Comment by Topfpflanze777** [comment]
quick update: NinjaIOUtils isn't loading again. I loaded the starwars pack by Barrel and your Invisible pack and everything worked fine, but after trying to reload it got stuck on the reloadscreen again. 
![Errormessages2](https://github.com/itzTheMeow/NinjaIOUtils/assets/174017356/ef5247cb-dde5-421d-acba-7f04e621ebaa)
![Errormessages3](https://github.com/itzTheMeow/NinjaIOUtils/assets/174017356/9946d2e3-9f13-498e-8484-02ed082f6428)

**Comment by itzTheMeow** [comment]
do you have other extensions enabled like an ad blocker? try disabling those

**Comment by Topfpflanze777** [comment]
Ok I disabled my Adblocker right now and all seems working fine! Thanks alot! Now I only have to figure out how to get my texturpack running . . .

**Comment by itzTheMeow** [comment]
are you using the zip upload?

**Comment by Topfpflanze777** [comment]
yes

**Comment by Topfpflanze777** [comment]
Wait, I will try sending a video

**Comment by Topfpflanze777** [comment]
Ok I just relized after the recording that you can only see the browser and not the little addon window or my explorer but the onlything you need to know is that everytime the game doesnt load is when I had NinjaIOUtils enabled

**Comment by Topfpflanze777** [comment]
https://www.youtube.com/watch?v=cRm9yOA6wQ8

**Comment by Topfpflanze777** [comment]
And about the file I uploaded to Ninja.io, everything in this screenshot is in there: 
![Texturpack contents](https://github.com/itzTheMeow/NinjaIOUtils/assets/174017356/239262e4-07b1-44d6-b20c-5b83561b4f3b)

**Comment by Topfpflanze777** [comment]
> Ok I disabled my Adblocker right now and all seems working fine! Thanks alot! Now I only have to figure out how to get my texturpack running . . .

Now it doesnt work anymore ...

**Comment by itzTheMeow** [comment]
You need to rename the `_meta (1)` file to just be `_meta`

**Comment by Topfpflanze777** [comment]
Ok i did that but the main problem is still that the skrip isn't working . . . since everytime I try to load any texturpack it gets stuck on the loadingscreen. I tried reinstalling and resetting everything 8 times but somehow it isn't working.

**Comment by itzTheMeow** [comment]
Is it any texture pack or just a custom .zip?

**Comment by Topfpflanze777** [comment]
any texturpack

**Comment by itzTheMeow** [comment]
i'm not sure how to help you since i can't reproduce the issue, sorry

**Comment by Topfpflanze777** [comment]
R.I.P.
